# Generated by Django 4.0.3 on 2022-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(help_text='200자 이하만', max_length=200),
        ),
    ]
